#!/bin/bash

if which riscv64-unknown-elf-gcc > /dev/null; then
    echo "riscv64-unknown-elf"
elif which riscv64-unknown-linux-gnu-gcc > /dev/null; then
    echo "riscv64-unknown-linux-gnu"
elif which riscv64-elf-gcc > /dev/null; then
    echo "riscv64-elf"
else
    exit 1
fi
