name: AllTests

on:
  push:
    branches:
      - main
      - actions/**
  pull_request:
    branches: [ main ]

jobs:
  test_c:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: make test test-gen2

  test_wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: cd wasm && npm install
    - name: test
      run:  make -C wasm test test-gen2
