name: AllTests

on:
  push:
    branches:
      - main
      - actions/**
  pull_request:
    branches: [ main ]

jobs:
  test_c:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: test
      run: make test test-gen2

  test_wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: npm ci
    - name: test
      run:  make test-wcc test-wcc-gen2
